from collections.abc import Iterable

def open_client(path: str) -> None: ...
def put(key: bytes, value: bytes) -> None: ...
def get(key: bytes) -> bytes | None: ...
def batch_get(keys: Iterable[bytes]) -> list[tuple[bytes, bytes]]: ...
def batch_put(pairs: Iterable[tuple[bytes, bytes]]) -> None: ...
def transactional_batch_put(pairs: Iterable[tuple[bytes, bytes]]) -> None: ...
def delete(key: bytes) -> None: ...
def batch_delete(keys: Iterable[bytes]) -> None: ...
def scan_prefix(prefix: bytes, limit: int) -> list[tuple[bytes, bytes]]: ...
def materialize_state_hamt(
    namespace: str,
    room_prefix: bytes,
    root_structural_hash: bytes,
    server_secret: bytes,
    room_id: str,
) -> list[tuple[str, str, str]] | None: ...
def materialize_state_hamts(
    namespace: str,
    server_secret: bytes,
    roots: list[tuple[bytes, bytes, str]],
) -> list[list[tuple[str, str, str]]]: ...
def lookup_state_hamts(
    namespace: str,
    queries: list[tuple[bytes, bytes, bytes, list[tuple[str, str]]]],
) -> list[list[tuple[str, str, str]]]: ...
