from collections.abc import Iterable

def room_structural_key(server_secret: bytes, room_id: str) -> bytes: ...
def build_root_handle(
    server_secret: bytes,
    room_id: str,
    entries: Iterable[tuple[str, str, str]],
) -> tuple[tuple[bytes, bytes], list[tuple[bytes, bytes]]]: ...
def materialize_state_entries(
    root_node_bytes: bytes,
    nodes: Iterable[tuple[bytes, bytes]],
) -> list[tuple[str, str, str]]: ...
def node_child_hashes(node_bytes: bytes) -> list[bytes]: ...
