from __future__ import annotations

from typing import Any, Callable

class MetricsFactory:
    def __init__(self) -> None: ...
    def create_counter(
        self, name: str, tags: dict[str, Any] | None = ...
    ) -> Callable[[int], None]: ...
    def create_timer(
        self, name: str, tags: dict[str, Any] | None = ...
    ) -> Callable[[float], None]: ...
    def create_gauge(
        self, name: str, tags: dict[str, Any] | None = ...
    ) -> Callable[[float], None]: ...

class LegacyMetricsFactory:
    def __init__(self, metrics_factory: MetricsFactory) -> None: ...
    def count(self, key: str, amount: int = ..., **kwargs: Any) -> None: ...
    def timing(self, key: str, amount: float = ..., **kwargs: Any) -> None: ...
    def gauge(self, key: str, amount: float = ..., **kwargs: Any) -> None: ...

class Metrics:
    def __init__(self, metrics_factory: MetricsFactory) -> None: ...
