from __future__ import annotations

from typing import Any, Callable

from .metrics import MetricsFactory

class PrometheusMetricsFactory(MetricsFactory):
    namespace: str
    def __init__(self, namespace: str = ...) -> None: ...
    def create_counter(
        self, name: str, tags: dict[str, Any] | None = ...
    ) -> Callable[[int], None]: ...
    def create_gauge(
        self, name: str, tags: dict[str, Any] | None = ...
    ) -> Callable[[float], None]: ...
