from __future__ import annotations

from concurrent.futures import Future
from typing import Any, Protocol

from .span import Span

class _Reporter(Protocol):
    def set_process(self, service_name: str, tags: Any, max_length: int) -> None: ...
    def report_span(self, span: Span) -> None: ...
    def close(self) -> Future[None]: ...

class Reporter(_Reporter):
    def __init__(self, channel: Any, **kwargs: Any) -> None: ...

class NullReporter(_Reporter): ...

class InMemoryReporter(_Reporter):
    def __init__(self) -> None: ...
    def get_spans(self) -> list[Span]: ...

class LoggingReporter(_Reporter):
    def __init__(self, logger: Any = ...) -> None: ...

class CompositeReporter(_Reporter):
    def __init__(self, *reporters: _Reporter) -> None: ...
