from __future__ import annotations

from concurrent.futures import Future
from typing import Any

from .span import Span

class BaseReporter:
    def set_process(self, service_name: str, tags: Any, max_length: int) -> None: ...
    def report_span(self, span: Span) -> None: ...
    def close(self) -> Future[None]: ...

class Reporter(BaseReporter):
    def __init__(self, channel: Any, **kwargs: Any) -> None: ...

class NullReporter(BaseReporter): ...

class InMemoryReporter(BaseReporter):
    def __init__(self) -> None: ...
    def get_spans(self) -> list[Span]: ...

class LoggingReporter(BaseReporter):
    def __init__(self, logger: Any = ...) -> None: ...

class CompositeReporter(BaseReporter):
    def __init__(self, *reporters: BaseReporter) -> None: ...
